const MAX_FLOORS=9,TOTAL_BOOKS=180;
const BOOK_COLORS=['#24372d','#293c31','#344031','#203830','#3e4030','#2e3c2d','#313c33'];
let currentExploreFloor=1;
const flatSentences=Object.entries(storyData).flatMap(([category,stories])=>stories.flatMap(story=>story.sentences.map(text=>({category,title:story.title,text}))));
// Keep the original mapping so existing book and story saves remain compatible.
const sentenceMap={};let sentenceIndex=7;
flatSentences.forEach(sentence=>{while(sentenceMap[sentenceIndex%TOTAL_BOOKS])sentenceIndex+=3;sentenceMap[sentenceIndex%TOTAL_BOOKS]=sentence;sentenceIndex+=13;});
function getFloorCost(floor){return Math.floor(50*Math.pow(1.8,floor-1));}
function getBookCost(floor){return Math.floor(30*Math.pow(1.5,floor-1));}
function showMessageModal(title,content,isConfirm=false,onConfirm=null){setText('modal-message-title',title);document.getElementById('modal-message-content').innerHTML=content;const yes=document.getElementById('modal-message-confirm'),no=document.getElementById('modal-message-cancel');yes.textContent=isConfirm?'确认':'知道了';no.style.display=isConfirm?'inline-block':'none';no.onclick=()=>closeModal('modal-message');yes.onclick=()=>{closeModal('modal-message');if(onConfirm)onConfirm();};openModal('modal-message');}
function updateFloorUI(){const unlocked=gameData.unlockedFloors.includes(currentExploreFloor),read=gameData.unlockedBooks.filter(i=>Math.floor(i/20)+1===currentExploreFloor).length;setText('explore-floor-title',`第 ${currentExploreFloor} 层`);setText('explore-floor-status',unlocked?`已阅 ${read} / 20 卷 · 首次翻阅 ${getBookCost(currentExploreFloor)} 方向感 · 重读免费`:`尚未解锁 · 开放本层需要 ${getFloorCost(currentExploreFloor)} 方向感`);for(const [id,disabled]of[['btn-floor-up',currentExploreFloor>=MAX_FLOORS],['btn-floor-down',currentExploreFloor<=1]]){document.getElementById(id).disabled=disabled;document.getElementById(id).classList.toggle('disabled',disabled);}initBookshelf();}
function changeFloor(delta){currentExploreFloor=Math.max(1,Math.min(MAX_FLOORS,currentExploreFloor+delta));updateFloorUI();}
document.getElementById('btn-floor-up').onclick=()=>changeFloor(1);document.getElementById('btn-floor-down').onclick=()=>changeFloor(-1);
window.addEventListener('keydown',e=>{if(!document.getElementById('page-explore').classList.contains('active')||document.querySelector('.modal.active')||document.getElementById('reading-overlay').classList.contains('active')||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();changeFloor(e.key==='ArrowUp'?1:-1);}});
function initBookshelf(){const container=document.getElementById('bookshelf-container');container.innerHTML='';for(let i=0;i<20;i++){const index=(currentExploreFloor-1)*20+i,read=gameData.unlockedBooks.includes(index),unlocked=gameData.unlockedFloors.includes(currentExploreFloor),sentence=sentenceMap[index],collected=sentence&&gameData.collectedFragments.includes(sentence.text);const book=document.createElement('button');book.className='book'+(!unlocked?' locked':read?' unlocked':'');book.style.setProperty('--book-color',BOOK_COLORS[index%BOOK_COLORS.length]);book.setAttribute('aria-label',`卷号 ${1024+index}，${collected?'片段已提取':read?'已阅，免费重读':unlocked?'未阅':'楼层未解锁'}`);book.innerHTML=`<small>${collected?'✦':read?'已阅':'未阅'}</small><span class="book-title">卷号 ${1024+index}</span><small>${String(i+1).padStart(2,'0')}</small>`;book.onclick=()=>tryOpenBook(index);container.appendChild(book);}}
function confirmSpend(title,cost,onConfirm){const balance=gameData.directionSense-cost;const warning=balance<=-10000?'<p style="color:#e4a48e">这次透支会触发「迷失」结局。</p>':balance<0?'<p style="color:#e4a48e">余额将为负数，恢复前光团收益减半。可以先回庭院积攒方向感。</p>':'';showMessageModal(title,`消耗 <strong>${cost}</strong> 方向感。<br>确认后余额约为 <strong>${Math.floor(balance)}</strong>。${warning}`,true,onConfirm);}
function tryOpenBook(index){if(!Number.isInteger(index)||index<0||index>=180)return;const floor=Math.floor(index/20)+1;if(!gameData.unlockedFloors.includes(floor)){const cost=getFloorCost(floor);confirmSpend('解锁第 '+floor+' 层',cost,()=>{if(gameData.unlockedFloors.includes(floor))return;gameData.directionSense-=cost;gameData.unlockedFloors.push(floor);saveGame();updateUI();updateFloorUI();});return;}if(gameData.unlockedBooks.includes(index)){renderReadingInterface(index);return;}const cost=getBookCost(floor);confirmSpend('翻阅卷号 '+(1024+index),cost,()=>{if(gameData.unlockedBooks.includes(index))return;gameData.directionSense-=cost;gameData.unlockedBooks.push(index);saveGame();updateUI();updateFloorUI();if(gameData.directionSense>-10000&&!gameData.towerCompleted)renderReadingInterface(index);else if(document.getElementById('screen-ending').style.display!=='flex')renderReadingInterface(index);});}
const readingContent=document.getElementById('reading-content');
function renderReadingInterface(index){const assigned=sentenceMap[index];let seed=index+1024;let gibberish='';const count=Math.min(900,Math.max(260,Math.floor(window.innerWidth*window.innerHeight/700)));for(let i=0;i<count;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;gibberish+=String.fromCharCode(0x4e00+seed%15000);}readingContent.replaceChildren();if(assigned){const pos=Math.floor(count*.35);readingContent.append(document.createTextNode(gibberish.slice(0,pos)));const sentence=document.createElement('span');sentence.textContent=assigned.text;if(!gameData.collectedFragments.includes(assigned.text)){sentence.className='meaningful-sentence';sentence.tabIndex=0;sentence.setAttribute('role','button');sentence.setAttribute('aria-label','提取故事片段：'+assigned.text);sentence.onclick=()=>extractSentenceFree(sentence,assigned);sentence.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();sentence.click();}};}else sentence.className='collected-sentence';readingContent.append(sentence,document.createTextNode(gibberish.slice(pos)));}else readingContent.textContent=gibberish;
 setText('reading-book-label',`第 ${Math.floor(index/20)+1} 层 · 卷号 ${1024+index}`);readingContent.style.setProperty('--mouse-x','50%');readingContent.style.setProperty('--mouse-y','40%');document.getElementById('reading-overlay').classList.add('active');document.getElementById('reading-overlay').scrollTop=0;document.getElementById('btn-close-reading').focus();}
function extractSentenceFree(element,assigned){if(gameData.collectedFragments.includes(assigned.text))return;gameData.collectedFragments.push(assigned.text);const story=storyData[assigned.category].find(s=>s.title===assigned.title);const completed=story.sentences.every(s=>gameData.collectedFragments.includes(s));if(completed&&!gameData.completedStories.includes(story.title))gameData.completedStories.push(story.title);element.className='collected-sentence';element.onclick=null;element.onkeydown=null;element.removeAttribute('role');element.removeAttribute('tabindex');saveGame();updateUI();initBookshelf();showMessageModal(completed?'故事已还原':'发现故事片段',`<p>${assigned.text}</p><p>${assigned.title} · ${assigned.category}</p><p style="color:#d8b477">${completed?'本次片段 +1%，完整故事额外 +10%':'光团价值加成 +1%'}（本周目）</p>`);}
function moveLight(e){const rect=readingContent.getBoundingClientRect();readingContent.style.setProperty('--mouse-x',(e.clientX-rect.left)+'px');readingContent.style.setProperty('--mouse-y',(e.clientY-rect.top)+'px');}
readingContent.addEventListener('pointermove',moveLight);readingContent.addEventListener('pointerdown',moveLight);
document.getElementById('reading-light').onchange=e=>readingContent.classList.toggle('full-light',e.target.checked);
readingContent.addEventListener('focusin',()=>{readingContent.classList.add('full-light');document.getElementById('reading-light').checked=true;});
document.getElementById('btn-close-reading').onclick=()=>{document.getElementById('reading-overlay').classList.remove('active');document.querySelector('.book')?.focus();};updateFloorUI();
