let toastTimer;
function toast(message){document.querySelector('.toast')?.remove();clearTimeout(toastTimer);const e=document.createElement('div');e.className='toast';e.setAttribute('role','status');e.textContent=message;document.body.appendChild(e);toastTimer=setTimeout(()=>e.remove(),3000);}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));
document.getElementById('goal-action').onclick=()=>{if(gameData.frogSpeedLevel>0&&!gameData.unlockedBooks.length)navigate('page-explore');else document.getElementById('frog').click();};
const frog=document.getElementById('frog');frog.setAttribute('role','button');frog.tabIndex=0;frog.setAttribute('aria-label','培养守馆青蛙');frog.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();frog.click();}});
let previousFocus=null;
const modalObserver=new MutationObserver(()=>{const modal=[...document.querySelectorAll('.modal.active')].pop();if(modal&&!modal.contains(document.activeElement)){previousFocus=document.activeElement;modal.querySelector('button:not(:disabled),input')?.focus();}else if(!modal&&previousFocus){previousFocus.focus();previousFocus=null;}});
document.querySelectorAll('.modal').forEach(m=>{m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');const title=m.querySelector('h2,h3');if(title){if(!title.id)title.id=m.id+'-title';m.setAttribute('aria-labelledby',title.id);}modalObserver.observe(m,{attributes:true,attributeFilter:['class']});});
window.addEventListener('keydown',e=>{const modal=[...document.querySelectorAll('.modal.active')].pop();if(e.key==='Escape'){if(modal)closeModal(modal.id);else document.getElementById('reading-overlay').classList.remove('active');}if(e.key==='Tab'&&modal){const buttons=[...modal.querySelectorAll('button:not(:disabled),input,[tabindex="0"]')].filter(x=>x.offsetParent!==null);if(!buttons.length)return;const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
