const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
// Small fake DOM exercises script initialization and game transactions without a browser.
function boot(saved){const html=fs.readFileSync('index.html','utf8'),ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,'duplicate ids');
 class Element{constructor(){this.style={setProperty(k,v){this[k]=v;}};this.dataset={};this.children=[];this.className='';this.textContent='';this.value='';this.disabled=false;this.isConnected=true;this.offsetParent={};this.classList={add(){},remove(){},contains(){return false},toggle(){}};}appendChild(e){this.children.push(e);return e;}append(...es){this.children.push(...es);}replaceChildren(...es){this.children=es;}remove(){this.isConnected=false;}setAttribute(){}removeAttribute(){}addEventListener(){}querySelector(){return new Element();}querySelectorAll(){return [];}get firstElementChild(){return this.children[0];}get scrollHeight(){return 0;}focus(){}contains(){return false;}getBoundingClientRect(){return{left:0,top:0}}}
 const nodes=Object.fromEntries(ids.map(id=>[id,new Element()]));const doc={getElementById:id=>nodes[id]||null,querySelectorAll:()=>[],querySelector:selector=>selector.startsWith('.col-tab-btn')?new Element():null,createElement:()=>new Element(),createTextNode:s=>s,body:new Element(),addEventListener(){},hidden:false};
 const stored=new Map(saved?[['babel_library_save',JSON.stringify(saved)]]:[]);const ctx=vm.createContext({document:doc,window:{innerWidth:1280,innerHeight:900,addEventListener(){}},localStorage:{getItem:k=>stored.get(k)||null,setItem:(k,v)=>stored.set(k,v)},location:{reload(){}},setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,MutationObserver:class{observe(){}},console,Date,Math});
 for(const src of [...html.matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]))vm.runInContext(fs.readFileSync(src,'utf8'),ctx,{filename:src});return{ctx,nodes,stored,run:code=>vm.runInContext(code,ctx)};}
test('all production scripts initialize on a fresh save',()=>{const app=boot();assert.equal(app.run('gameData.babelFloor'),1);assert.equal(app.run('gameData.unlockedBooks.length'),0);assert.ok(app.stored.has('babel_library_save'));});
test('99th floor reward is applied once and tower cannot restart',()=>{const app=boot({babelFloor:99,babelOrbBonus:0});app.run("startNewBattle();battleState.enemy.hp=1;processTurn(battleState.player.hand.find(id=>['combat','crime','creation','education','service'].includes(id)))");assert.equal(app.run('gameData.towerCompleted'),true);const bonus=app.run('gameData.babelOrbBonus');app.run('startNewBattle()');assert.equal(app.run('gameData.babelOrbBonus'),bonus);});
test('purchase confirmation captures its own floor even if navigation changes',()=>{const app=boot();app.run('currentExploreFloor=2;tryOpenBook(20);currentExploreFloor=3');app.nodes['modal-message-confirm'].onclick();assert.deepEqual(JSON.parse(app.run('JSON.stringify(gameData.unlockedFloors)')),[1,2]);assert.equal(app.run('gameData.directionSense'),-90);});
test('re-reading an owned book does not charge again',()=>{const app=boot({directionSense:100,unlockedBooks:[7]});app.run('tryOpenBook(7)');assert.equal(app.run('gameData.directionSense'),100);});
test('duplicate fragment clicks only award once',()=>{const app=boot();app.run("extractSentenceFree(document.createElement('span'),sentenceMap[7]);extractSentenceFree(document.createElement('span'),sentenceMap[7])");assert.equal(app.run('gameData.collectedFragments.length'),1);});
test('negative, fractional and infinite bets cannot alter the economy',()=>{const app=boot({babelFloor:4,directionSense:100});app.run('startNewBattle()');for(const value of ['-1','0.5','1e309']){app.nodes['dice-bet-input'].value=value;app.nodes['btn-roll-dice'].onclick();assert.equal(app.run('gameData.directionSense'),100);assert.equal(app.run('battleState.turn'),1);}});
test('battle restore retains previous state without issuing rewards',()=>{const app=boot();app.run("startNewBattle();processTurn(battleState.player.hand.find(id=>['combat','crime','creation','education','service'].includes(id)))");const saved=JSON.parse(app.stored.get('babel_library_save'));saved.lastSaveTime=Date.now();const next=boot(saved);assert.equal(next.run('battleState.turn'),2);assert.equal(next.run('gameData.babelFloor'),1);});
