const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const html=fs.readFileSync('multiplayer.html','utf8');const source=html.match(/<script>\s*([\s\S]*?)<\/script>/)[1];
function pair(){const queue=[],sessions=[];for(let i=0;i<2;i++){const els=new Map();const element=()=>({style:{},children:[],value:'旅人'+i,innerText:'',innerHTML:'',textContent:'',appendChild(e){this.children.push(e)},setAttribute(){}});const document={getElementById(id){if(!els.has(id))els.set(id,element());return els.get(id)},createElement:element};const c=vm.createContext({document,console,setTimeout:()=>0,setInterval:()=>0,clearInterval(){},navigator:{},Math});vm.runInContext(source,c);c.sendMessage=data=>queue.push({to:1-i,data:JSON.parse(JSON.stringify(data))});vm.runInContext(`conn={send:sendMessage};isHost=${i===0};`,c);sessions.push({c,run:code=>vm.runInContext(code,c)});}
function flush(){let n=0;while(queue.length){assert.ok(n++<100);const {to,data}=queue.shift();sessions[to].c.packet=data;sessions[to].run('handleData(packet)');}}
return {sessions,flush};}
test('two simulated peers agree on health and turns through multiple redeals',()=>{const p=pair();p.sessions[0].run('initGameData(true)');p.flush();for(let turn=0;turn<24;turn++){const actor=p.sessions.find(s=>s.run('isMyTurn'));if(!actor)break;actor.run("{const i=me.hand.findIndex((c,i)=>!c.passive&&!(c.once&&me.usedCards.includes(i)));if(i>=0)playCard(me.hand[i],i);else{conn.send({type:'SKIP_TURN'});isMyTurn=false;checkTurnEnd(me,opp);}}");p.flush();const [a,b]=p.sessions;assert.equal(a.run('me.hp'),b.run('opp.hp'));assert.equal(a.run('opp.hp'),b.run('me.hp'));if(a.run('gameOver'))break;assert.notEqual(a.run('isMyTurn'),b.run('isMyTurn'));}});
test('multiplayer creation protects caster and repeat packet on wrong turn is ignored',()=>{const p=pair();const a=p.sessions[0];a.run("applyEffect(cardDB.find(c=>c.id==='creation'),me,opp);applyEffect(cardDB.find(c=>c.id==='combat'),opp,me)");assert.equal(a.run('me.hp'),28);a.run("gameOver=false;isMyTurn=true;opp.hand=[cardDB.find(c=>c.id==='crime')];processOpponentPlay('crime',0)");assert.equal(a.run('me.hp'),28);});
test('rematch clears counters, terminal state and both votes',()=>{const p=pair();p.sessions[0].run('playCount=5;rematchState={me:true,opp:true};gameOver=true;initGameData(true)');p.flush();for(const s of p.sessions){assert.equal(s.run('gameOver'),false);assert.equal(s.run('playCount'),0);assert.equal(s.run('rematchState.me||rematchState.opp'),false);}});
test('invalid remote card ids and hands cannot crash or alter local state',()=>{const p=pair();const s=p.sessions[1];s.run("handleData({type:'START_GAME',yourHand:[{id:'bogus'}],oppHand:[]});processOpponentPlay('bogus',0)");assert.equal(s.run('gameOver'),true);assert.equal(s.run('me.hp'),30);});
